name: Rhett Burch
favicon: null
layout_spectrum: 0.930064158514142
typography_spectrum: 0.0050312792882323265
title: 'rhettburch '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#e0dbe1'
    - '#7d645f'
    - '#a392a4'
    - '#7a2e0e'
  brandStrength: 0.9923824733123183
  lightness: 0.5894749099388719
  saturation: 0.520944168092683
  rhythmicContrast: 0.210692816413939
purpose: []
